spring:
  application:
    name: beershop
  datasource.url: jdbc:postgresql:postgres
  jpa:
    properties :
      hibernate :
        jdbc :
          lob :
            non_contextual_creation : true
